### ISSUE TITLE
Redox and water temp are sometimes set to 0 when REGUL SALT 4 is power on.

### ISSUE THREAD

**Issue by christopheBfr** [sylvaing/Hackeron#6]
![water_temp_0_at_akeron_startup](https://github.com/sylvaing/Hackeron/assets/43133099/084b4455-5e4d-4073-8c2b-78ddbf3fae07)
Hello Sylvain

When the programatic clock is starting the water pump and the REGUL Akeron Duo Salt 4 Rx (on the same time on my system), sometimes, the water temp and rx value are set to 0 for the first value (just after the power on).

On my side, to avoid that, I changed a little bit your code (sorry , I didn't define the git link to your github projet yet...) , but can you add also the following changes to avoid "0" values that can occurs on Rx value and water temp value ?

if ((hackeron.temp.Value <= 50) && (hackeron.temp.Value >= 0)
becomes 
if ((hackeron.temp.Value <= 50) && (hackeron.temp.Value > 0)

=> Strict grater than (not equal) to avoid 0 values.

in the code, the update must be done several times for each parameter rx or water temp.

I attached the files updated (note that I also update the code to report water temp to HA after a minimum of time interval (in order to let the pool water circulate enough after a "water pump power on" ). Without this update , in the morning , when REGUL + water pump are started together (by the programmatic clock) , the first temp values are the water temperature that stayed in the pipes during the night, not the real swimming pool temp itself....   (you can take this litle update - or not - as you want.... But I only do the update for the temperature... not for the other parameters...)
[src.zip](https://github.com/sylvaing/Hackeron/files/11720344/src.zip)

And thx for the new Wifi update. ( according to wifi RSSI, it is sure that Akeron RX  DUO Salt 4 is not really "eletromagnetic - safe", the akeron device produce a lot of Wifi interferences... The Wifi reconnection can help....

**Comment by sylvaing** [comment]
Hi @christopheBfr , thank you for your contribution.

I have the same setup, my pump start with akeron, but I d'ont have 0 value for redox or temp. however, I agree with you to add strict greater to avoid 0 value, I will do this.

On the other hand, why do you want avoid to report temp (and others parameters) deteced by your akeron on start. I agree with you that is'nt the temp of the pool, but the water in the pipe. But I think that can be interresting to see this to view when the akeron make some thing on your water ( elx, ph injection, etc..) at start.
I'm interesting about utility for you.

**Comment by christopheBfr** [comment]
Hello @sylvaing 

For the temp HA report "skipping" during first 10 minuts, it was just to avoid false "pool temp measurement" or rx mesuerment... (these values tend to change very quickly during the first minuts when the pump is started). But it is not "critical" and there are no other automations linked to these parameters, so it is not very important to have very  precise values, so it is OK also to skip it... 
 
You can keep only the ">0" change, not the pool mesurement skiping during first minuts   😏

Regards

@christopheBfr
